# Generated by Django 4.1.12 on 2023-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('lev_operator', 'Lev Operator'), ('lev_engineer', 'Lev Engineer'), ('lev_manager', 'Lev Manager'), ('owner', 'Owner')], default='owner', max_length=20),
        ),
    ]
