# Generated by Django 5.1.1 on 2024-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_accounts_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user")],
                default="user",
                max_length=20,
            ),
        ),
    ]
